### ISSUE TITLE
我在知网上看到一篇论文与您的教程基本一致，请问是您发的吗？

### ISSUE THREAD

**Issue by zhen8838** [kadoufall/Urban-Sound-Classification-VS#1]
[论文链接](http://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFQ&dbname=CJFDLAST2019&filename=ZJGD201902015&uid=WEEvREcwSlJHSldRa1FhdXNXaEd2UnFndDNtZFV5OEVJWkNUdVczMkNZQT0=$9A4hF_YAuvQ5obgVAqNKPCYcEjKensW4IQMovwHtwkF4VYPoHbKxJw!!&v=MTY5ODF5Zk1hckc0SDlqTXJZOUVZWVI4ZVgxTHV4WVM3RGgxVDNxVHJXTTFGckNVUkxPZll1ZHBGeXpnVzd6TVA=)

**Comment by kadoufall** [comment]
不是的
