### ISSUE TITLE
我如何使用此模型跑自己的数据

### ISSUE THREAD

**Issue by liu-ioa** [kadoufall/Urban-Sound-Classification-VS#2]
自己录制了一些分类音频，怎么跑自己的数据集，我跑自己的数据提取mfcc特征时报出现维度错误。

**Comment by kadoufall** [comment]
> 自己录制了一些分类音频，怎么跑自己的数据集，我跑自己的数据提取mfcc特征时报出现维度错误。

整理成与原数据一样格式的`wav`音频文件和对应的分类描述`csv`文件。具体错误要截图看一下是什么…

**Comment by liu-ioa** [comment]
感谢回复！ 已经训练好的模型只能做理论分析吗？请问作者是否了解tensorflow lite，我想在移动端应用但是识别总是弹出同一个标签------------------ 原始邮件 ------------------
发件人: "kadoufall"<notifications@github.com>
发送时间: 2019年9月9日(星期一) 晚上6:37
收件人: "kadoufall/Urban-Sound-Classification-VS"<Urban-Sound-Classification-VS@noreply.github.com>;
抄送: "2834156593lq"<2834156593@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [kadoufall/Urban-Sound-Classification-VS] 我如何使用此模型跑自己的数据 (#2)


 
自己录制了一些分类音频，怎么跑自己的数据集，我跑自己的数据提取mfcc特征时报出现维度错误。
  
整理成与原数据一样格式的wav音频文&#x4EF6;和对应的分类描述csv文&#x4EF6;。具体错误要截图看一下是什么…
 
&mdash;

**Comment by kadoufall** [comment]
> 感谢回复！ 已经训练好的模型只能做理论分析吗？请问作者是否了解tensorflow lite，我想在移动端应用但是识别总是弹出同一个标签------------------ 原始邮件 ------------------ 发件人: "kadoufall"<notifications@github.com> 发送时间: 2019年9月9日(星期一) 晚上6:37 收件人: "kadoufall/Urban-Sound-Classification-VS"<Urban-Sound-Classification-VS@noreply.github.com>; 抄送: "2834156593lq"<2834156593@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [kadoufall/Urban-Sound-Classification-VS] 我如何使用此模型跑自己的数据 (#2) 自己录制了一些分类音频，怎么跑自己的数据集，我跑自己的数据提取mfcc特征时报出现维度错误。 整理成与原数据一样格式的wav音频文&#x4EF6;和对应的分类描述csv文&#x4EF6;。具体错误要截图看一下是什么… &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

这个项目是教学用的项目，只做了简单的分析，没有进一步开发了。你提到的TensorFlow Lite的情况我不了解，抱歉~

**Comment by liu-ioa** [comment]
嗯嗯，谢谢！------------------ 原始邮件 ------------------
发件人: "kadoufall"<notifications@github.com>
发送时间: 2019年9月9日(星期一) 晚上6:56
收件人: "kadoufall/Urban-Sound-Classification-VS"<Urban-Sound-Classification-VS@noreply.github.com>;
抄送: "2834156593lq"<2834156593@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [kadoufall/Urban-Sound-Classification-VS] 我如何使用此模型跑自己的数据 (#2)


 
感谢回复！ 已经训练好的模型只能做理论分析吗？请问作者是否了解tensorflow lite，我想在移动端应用但是识别总是弹出同一个标签------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "kadoufall"notifications@github.com 发送时间: 2019年9月9日(星期一) 晚上6:37 收&#x4EF6;人: "kadoufall/Urban-Sound-Classification-VS"Urban-Sound-Classification-VS@noreply.github.com; 抄送: "2834156593lq"2834156593@qq.com;"Author"author@noreply.github.com; 主题: Re: [kadoufall/Urban-Sound-Classification-VS] 我如何使用此模型跑自己的数据 (#2) 自己录制了一些分类音频，怎么跑自己的数据集，我跑自己的数据提取mfcc特征时报出现维度错误。 整理成与原数据一样格式的wav音频文&#x4EF6;和对应的分类描述csv文&#x4EF6;。具体错误要截图看一下是什么… — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
  
这个项目是教学用的项目，只做了简单的分析，没有进一步开发了。你提到的TensorFlow Lite的情况我不了解，抱歉~
 
&mdash;
